# Insert a blank line between shell prompts
add_newline = true

# Define the order and format of the information in our prompt
format = """$directory\
${custom.directory_separator_not_git}\
${custom.directory_separator_git}\
$symbol($git_branch(fg:#FCF392))\
$symbol($git_status)\
$character
"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'

# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

# Disable the line break between the first and second prompt lines
[line_break]
disabled = true

# Customize the format of the working directory
[directory]
truncate_to_repo = true
format = "[ $path ]($style)"
style = "fg:text"

[git_branch]
symbol = " "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#1C3A5E"

[git_status]
staged = "+(green)"
untracked = "?(red)"
modified = "*(yellow)"

[git_metrics]
disabled = false

[package]
format = " "

[custom.directory_separator_git]
description = "Output a styled separator right after the directory when inside a git repository."
command = ""
format = "[](fg:#3B76F0)"
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"

[custom.directory_separator_not_git]
description = "Output a styled separator right after the directory when NOT inside a git repository."
command = ""
format = "[⌂ ](fg:#3B76F0)"
when = "! git rev-parse --is-inside-work-tree > /dev/null 2>&1"
